/**
 * Auto-generated icon data file
 * Generated by scripts/generate-icons.js at build time
 * Do not edit this file manually
 */

const iconSvgData: Record<string, string> = {

};

export function getIconSvg(iconName: string): string {
    return iconSvgData[iconName] || "";
}

export function hasIcon(iconName: string): boolean {
    return iconName in iconSvgData;
}

export default iconSvgData;
