/**
 * Icon preprocessing script (Twilight version)
 * Automatically scan icons used in Svelte and Astro components during build and generate inline SVG data
 * 
 * Logic:
 * 1. Scan .svelte and .astro files in src directory
 * 2. Extract all icons in the form of icon="prefix:name"
 * 3. Read SVG data from node_modules/@iconify-json/[prefix]/icons.json
 * 4. Generate src/utils/icons.ts
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, "..");
const SRC_DIR = join(ROOT_DIR, "src");
const OUTPUT_FILE = join(SRC_DIR, "utils", "icons.ts");

// Supported icon sets and their package names
const ICON_SETS = {
    "material-symbols": "@iconify-json/material-symbols",
    "fa6-solid": "@iconify-json/fa6-solid",
    "fa6-brands": "@iconify-json/fa6-brands",
    "fa6-regular": "@iconify-json/fa6-regular",
    "mdi": "@iconify-json/mdi",
    "eos-icons": "@iconify-json/eos-icons",
};

// Icon set data cache
const iconSetCache = new Map();

/**
 * Recursively get all files in directory
 */
function getAllFiles(dir, extensions = [".svelte", ".astro"]) {
    const files = [];

    function walk(currentDir) {
        if (!existsSync(currentDir)) return;
        const items = readdirSync(currentDir);
        for (const item of items) {
            const fullPath = join(currentDir, item);
            const stat = statSync(fullPath);

            if (stat.isDirectory()) {
                if (!item.startsWith(".") && item !== "node_modules" && item !== "dist") {
                    walk(fullPath);
                }
            } else if (extensions.some((ext) => item.endsWith(ext))) {
                files.push(fullPath);
            }
        }
    }

    walk(dir);
    return files;
}

/**
 * Extract icon names from file content
 */
function extractIconNames(content) {
    const icons = new Set();

    // Match various icon usage patterns
    const patterns = [
        // icon="xxx:yyy" or icon='xxx:yyy'
        /icon=["']([a-z0-9-]+:[a-z0-9-]+)["']/gi,
        // icon={`xxx:yyy`}
        /icon=\{[`"']([a-z0-9-]+:[a-z0-9-]+)[`"']\}/gi,
    ];

    for (const pattern of patterns) {
        let match;
        while ((match = pattern.exec(content)) !== null) {
            icons.add(match[1]);
        }
    }

    return icons;
}

/**
 * Load icon set data
 */
function loadIconSet(prefix) {
    if (iconSetCache.has(prefix)) {
        return iconSetCache.get(prefix);
    }

    const packageName = ICON_SETS[prefix];
    if (!packageName) {
        console.warn(`⚠️  Unknown icon set: ${prefix}`);
        return null;
    }

    try {
        const iconSetPath = join(ROOT_DIR, "node_modules", packageName, "icons.json");
        if (!existsSync(iconSetPath)) {
            console.warn(`⚠️  Icon set file not found: ${iconSetPath}`);
            return null;
        }
        const data = JSON.parse(readFileSync(iconSetPath, "utf-8"));
        iconSetCache.set(prefix, data);
        return data;
    } catch (error) {
        console.warn(`⚠️  Cannot load icon set ${packageName}: ${error.message}`);
        return null;
    }
}

/**
 * Get SVG for a single icon
 */
function getIconSvg(iconName) {
    const [prefix, name] = iconName.split(":");
    if (!prefix || !name) return null;

    const iconSet = loadIconSet(prefix);
    if (!iconSet) return null;

    const iconData = iconSet.icons[name];
    if (!iconData) {
        // Try to find from aliases
        if (iconSet.aliases && iconSet.aliases[name]) {
            const alias = iconSet.aliases[name];
            const realName = alias.parent;
            const realData = iconSet.icons[realName];
            if (realData) {
                return buildSvg(realData, iconSet);
            }
        }
        console.warn(`⚠️  Icon not found: ${iconName}`);
        return null;
    }

    return buildSvg(iconData, iconSet);
}

function buildSvg(iconData, iconSet) {
    const width = iconData.width || iconSet.width || 24;
    const height = iconData.height || iconSet.height || 24;
    const body = iconData.body;

    // Simple SVG building
    return `<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 ${width} ${height}" fill="currentColor">${body}</svg>`;
}

/**
 * Generate icons.ts file
 */
function generateIconsFile(iconsMap) {
    const iconEntries = Array.from(iconsMap.entries())
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([name, svg]) => `\t"${name}":\n\t\t'${svg.replace(/'/g, "\\'")}'`)
        .join(",\n");

    return `/**
 * Auto-generated icon data file
 * Generated by scripts/generate-icons.js at build time
 * Do not edit this file manually
 */

const iconSvgData: Record<string, string> = {
${iconEntries}
};

export function getIconSvg(iconName: string): string {
    return iconSvgData[iconName] || "";
}

export function hasIcon(iconName: string): boolean {
    return iconName in iconSvgData;
}

export default iconSvgData;
`;
}

/**
 * Main logic
 */
async function main() {
    console.log("🚀 Starting icon scan...");
    const files = getAllFiles(SRC_DIR);
    const allIcons = new Set();

    for (const file of files) {
        const content = readFileSync(file, "utf-8");
        const icons = extractIconNames(content);
        for (const icon of icons) {
            allIcons.add(icon);
        }
    }

    console.log(`📦 Found ${allIcons.size} unique icons`);

    const iconsMap = new Map();
    for (const icon of allIcons) {
        const svg = getIconSvg(icon);
        if (svg) {
            iconsMap.set(icon, svg);
        }
    }

    const outputDir = dirname(OUTPUT_FILE);
    if (!existsSync(outputDir)) {
        mkdirSync(outputDir, { recursive: true });
    }

    writeFileSync(OUTPUT_FILE, generateIconsFile(iconsMap));
    console.log(`✅ Generated ${OUTPUT_FILE}`);
}

main().catch(console.error);